### ISSUE TITLE
Editor Crashes After Project Loaded

### ISSUE THREAD

**Issue by chfanghr** [webbertakken/unity-test-runner#73]
[log](https://github.com/chfanghr/UnityFSM/runs/1187445107?check_suite_focus=true#step:5:3640)

```
[Project] Loading completed in 112.992 seconds
	Project init time: 				0.318 seconds
		Template init time: 		0.000 seconds
		Package Manager init time: 		0.000 seconds
		Asset Database init time: 		0.000 seconds
		Global illumination init time: 	0.000 seconds
		Assemblies load time: 			0.000 seconds
		Unity extensions init time: 	0.001 seconds
		Asset Database refresh time: 	0.000 seconds
	Scene opening time: 			0.328 seconds
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 12 stack frames.
#0  0x007f613be3a8a0 in funlockfile
#1  0x0055e34f41cfc3 in GetNetActiveWindow()
#2  0x0055e34f41ce96 in CloseStaleAuxWindows()
#3  0x0055e34f42c2f5 in CheckFocus(void*)
#4  0x007f613cc20d03 in g_source_get_time
#5  0x007f613cc20285 in g_main_context_dispatch
#6  0x007f613cc20650 in g_main_context_dispatch
#7  0x007f613cc20962 in g_main_loop_run
#8  0x007f613e9cfa25 in gtk_main
#9  0x0055e34f42b87a in main
#10 0x007f613ba58b97 in __libc_start_main
#11 0x0055e34c29ae9f in _start
Segmentation fault (core dumped)
Unexpected exit code 139

###########################
#    Project directory    #
###########################

/steps/run_tests.sh: line 106: [: =: unary operator expected
total 56K
drwxr-xr-x 12 1001  116 4.0K Sep 30 07:44 .
drwxr-xr-x  5 root root 4.0K Sep 30 07:44 ..
drwxr-xr-x  9 1001  116 4.0K Sep 30 07:41 .git
-rw-r--r--  1 1001  116 2.0K Sep 30 07:41 .gitattributes
drwxr-xr-x  3 1001  116 4.0K Sep 30 07:41 .github
-rw-r--r--  1 1001  116  336 Sep 30 07:41 .gitignore
drwxr-xr-x  4 1001  116 4.0K Sep 30 07:41 Assets
drwxr-xr-x  9 root root 4.0K Sep 30 07:46 Library
drwxr-xr-x  2 root root 4.0K Sep 30 07:44 Logs
drwxr-xr-x  2 1001  116 4.0K Sep 30 07:44 Packages
drwxr-xr-x  2 1001  116 4.0K Sep 30 07:41 ProjectSettings
drwxr-xr-x  2 root root 4.0K Sep 30 07:46 Temp
drwxr-xr-x  2 1001  116 4.0K Sep 30 07:41 UserSettings
drwxr-xr-x  2 root root 4.0K Sep 30 07:44 editmode-artifacts

###########################
#    Edit Mode Results    #
###########################

cat: /github/workspace/editmode-artifacts/editmode-results.xml: No such file or directory
cat: /github/workspace/editmode-artifacts/editmode-results.xml: No such file or directory
/steps/run_tests.sh: line 157: [: =: unary operator expected
/steps/run_tests.sh: line 175: [: -gt: unary operator expected
Error: The process '/usr/bin/docker' failed with exit code 139
```

**Comment by webbertakken** [comment]
Closing issue because there are no words in it. (it also doesn't show the actual error and doesn't use the latest version).

**Comment by GabLeRoux** [comment]
I quickly looked at the linked log. This could be related (it's possible that it's totally normal too):

```
Symbol file LoadedFromMemory doesn't match image /github/workspace/Library/PackageCache/com.unity.ext.nunit@1.0.0/net35/unity-custom/nunit.framework.dll
Native extension for LinuxStandalone target not found
```

@chfanghr you should add more context such as what you tried, what is different in your project compared to a blank project. Did it work before or is this the first time you setup the project. Etc.

Good luck :v:
